version: '3.8'

services:
  # ATS Document Converter Service
  ats-converter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.optimized
    image: ats-document-converter:latest
    container_name: ats-document-converter
    volumes:
      - ../examples:/app/input
      - ../output:/app/output
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    # Remove container after execution
    restart: "no"

  # Development service
  ats-converter-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: ats-document-converter:dev
    container_name: ats-document-converter-dev
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - DEBUG=1
    # Keep container running for development
    command: ["tail", "-f", "/dev/null"]
    restart: "unless-stopped"
    profiles:
      - dev

  # Task-focused service example - run conversion and exit
  ats-convert-task:
    build:
      context: ..
      dockerfile: docker/Dockerfile.optimized
    image: ats-document-converter:latest
    container_name: ats-convert-task
    volumes:
      - ../examples:/app/input
      - ../output:/app/output
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    # Example: docker-compose run --rm ats-convert-task /app/input/sample.md -o /app/output/sample.pdf
    restart: "no"
    profiles:
      - task
