services:
  # ATS Document Converter - Optimized Version
  ats-converter-optimized:
    build:
      context: ..
      dockerfile: docker/Dockerfile.optimized
    image: ats-document-converter:optimized
    container_name: ats-document-converter-optimized
    volumes:
      - ../examples:/app/input
      - ../output:/app/output
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    # Remove container after execution
    restart: "no"


  # ATS Document Converter - Alpine Version (Minimal)
  ats-converter-alpine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.alpine
    image: ats-document-converter:alpine
    container_name: ats-document-converter-alpine
    volumes:
      - ../examples:/app/input
      - ../output:/app/output
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    # Remove container after execution
    restart: "no"

  # Development service (using optimized version)
  ats-converter-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: ats-document-converter:dev-optimized
    container_name: ats-document-converter-dev
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - DEBUG=1
    # Keep container running for development
    command: ["tail", "-f", "/dev/null"]
    restart: "unless-stopped"
    profiles:
      - dev
