name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run CI on'
        required: false
        default: 'main'
        type: string

env:
  CI: true
  UV_COMPILE_BYTECODE: 1
  CI_STRICT_SECURITY: true

jobs:
  build:
    name: Build & Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Extract Python version
        id: python-version
        run: echo "version=$(./scripts/extract-versions.sh python)" >> $GITHUB_OUTPUT

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: latest
          enable-cache: false
          activate-environment: true
          python-version: ${{ steps.python-version.outputs.version }}


      - name: Extract Node.js version
        id: node-version
        run: echo "version=$(./scripts/extract-versions.sh node)" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Extract pnpm version
        id: pnpm-version
        run: echo "version=$(./scripts/extract-versions.sh pnpm)" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        env:
          NODE_OPTIONS: "--trace-deprecation"
        with:
          version: ${{ steps.pnpm-version.outputs.version }}

      - name: Extract hadolint version
        id: hadolint-version
        run: echo "version=$(./scripts/extract-versions.sh hadolint)" >> $GITHUB_OUTPUT

      - name: Install system dependencies
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y shellcheck
          # Download hadolint binary and checksum file securely
          curl -fL https://github.com/hadolint/hadolint/releases/download/v${{ steps.hadolint-version.outputs.version }}/hadolint-linux-x86_64 -o hadolint-linux-x86_64
          curl -fL https://github.com/hadolint/hadolint/releases/download/v${{ steps.hadolint-version.outputs.version }}/hadolint-linux-x86_64.sha256 -o hadolint-linux-x86_64.sha256
          # Verify checksum before installation
          sha256sum -c hadolint-linux-x86_64.sha256
          chmod +x hadolint-linux-x86_64
          sudo mv hadolint-linux-x86_64 /usr/local/bin/hadolint

      - name: Install mise
        uses: jdx/mise-action@v3
        env:
          NODE_OPTIONS: "--trace-deprecation"
        with:
          version: 2025.10.6
          install: true
          cache: true

      - name: Install project dependencies
        run: just install

      - name: Run CI checks
        run: just ci

  test:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          version: 2025.10.6
          install: true
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test Docker images
        run: |
          just _ci-build-docker
          just _ci-test-docker

      - name: Extract hadolint version
        id: hadolint-version-publish
        run: echo "version=$(./scripts/extract-versions.sh hadolint)" >> $GITHUB_OUTPUT

      - name: Validate Dockerfiles
        run: |
          set -e
          # Download hadolint binary and checksum file securely
          curl -fL https://github.com/hadolint/hadolint/releases/download/v${{ steps.hadolint-version-publish.outputs.version }}/hadolint-linux-x86_64 -o hadolint-linux-x86_64
          curl -fL https://github.com/hadolint/hadolint/releases/download/v${{ steps.hadolint-version-publish.outputs.version }}/hadolint-linux-x86_64.sha256 -o hadolint-linux-x86_64.sha256
          # Verify checksum before installation
          sha256sum -c hadolint-linux-x86_64.sha256
          chmod +x hadolint-linux-x86_64
          sudo mv hadolint-linux-x86_64 /usr/local/bin/hadolint
          just validate-dockerfiles


  publish:
    name: Publish (on main)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          version: 2025.10.6
          install: true
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker images
        run: just publish latest
