name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  UV_COMPILE_BYTECODE: 1
  UV_CACHE_DIR: ~/.cache/uv
  UV_INDEX_STRATEGY: unsafe-best-match

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.8.18"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}-
            ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}-
            ${{ runner.os }}-uv-

      - name: Show UV version info
        run: |
          echo "UV Version: $(uv --version)"
          echo "Python Version: $(uv run python --version)"
          echo "UV Cache Directory: $UV_CACHE_DIR"

      - name: Install dependencies
        run: uv sync --dev

      - name: Install additional tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o hadolint
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run quality checks
        run: ./scripts/quality-check.sh

  docker-test:
    name: Docker Image Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test existing Docker images
        run: |
          echo "🧪 Testing existing Docker images..."
          ./scripts/test-docker-images.sh

      - name: Build and test new Docker images
        run: |
          echo "🔨 Building and testing new Docker images..."
          ./scripts/build-all-images.sh

      - name: Generate Dockerfiles
        run: |
          echo "📝 Generating Dockerfiles with shared patterns..."
          ./scripts/generate-dockerfiles.sh

      - name: Validate Dockerfiles
        run: |
          echo "✅ Validating Dockerfiles..."
          # Test that Dockerfiles are valid with correct build context
          docker build -f docker/Dockerfile.alpine -t test-alpine . > /dev/null 2>&1
          docker build -f docker/Dockerfile.optimized -t test-optimized . > /dev/null 2>&1
          docker build -f docker/Dockerfile.dev -t test-dev . > /dev/null 2>&1
          echo "✅ All Dockerfiles are valid"


  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [quality, docker-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build multi-arch images for scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.optimized
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ats-pdf-generator:optimized-scan
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            VENDOR=DohDa Labs
            UV_CACHE_DIR=/tmp/uv-cache
            BUILDKIT_INLINE_CACHE=1

      - name: Build Alpine image for scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ats-pdf-generator:alpine-scan
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            VENDOR=DohDa Labs
            UV_CACHE_DIR=/tmp/uv-cache
            BUILDKIT_INLINE_CACHE=1

      - name: Build Dev image for scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.dev
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ats-pdf-generator:dev-scan
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            VENDOR=DohDa Labs
            UV_CACHE_DIR=/tmp/uv-cache
            BUILDKIT_INLINE_CACHE=1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ats-pdf-generator:alpine-scan'
          format: 'sarif'
          output: 'trivy-results-alpine.sarif'
        continue-on-error: true

      - name: Run Trivy vulnerability scanner (Optimized)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ats-pdf-generator:optimized-scan'
          format: 'sarif'
          output: 'trivy-results-optimized.sarif'
        continue-on-error: true

      - name: Run Trivy vulnerability scanner (Dev)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ats-pdf-generator:dev-scan'
          format: 'sarif'
          output: 'trivy-results-dev.sarif'
        continue-on-error: true

      - name: Check SARIF files exist
        run: |
          echo "Checking for SARIF files..."
          ls -la *.sarif || echo "No SARIF files found"
          if [ -f "trivy-results-alpine.sarif" ]; then
            echo "✅ trivy-results-alpine.sarif exists"
          else
            echo "❌ trivy-results-alpine.sarif not found"
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main' && hashFiles('trivy-results-alpine.sarif') != ''
        with:
          sarif_file: 'trivy-results-alpine.sarif'
        continue-on-error: true

  publish:
    name: Publish (on main)
    runs-on: ubuntu-latest
    needs: [quality, docker-test, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish multi-arch images with rich tags
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.optimized
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ats-pdf-generator:latest
            ats-pdf-generator:optimized
            ats-pdf-generator:${{ github.sha }}
            ghcr.io/dohdalabs/ats-pdf-generator:latest
            ghcr.io/dohdalabs/ats-pdf-generator:optimized
            ghcr.io/dohdalabs/ats-pdf-generator:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            VENDOR=DohDa Labs
            UV_CACHE_DIR=/tmp/uv-cache
            BUILDKIT_INLINE_CACHE=1

      - name: Publish Alpine images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ats-pdf-generator:alpine
            ghcr.io/dohdalabs/ats-pdf-generator:alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            VENDOR=DohDa Labs
            UV_CACHE_DIR=/tmp/uv-cache
            BUILDKIT_INLINE_CACHE=1

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [quality, docker-test, security-scan, publish]
    if: always()
    steps:
      - name: Generate summary
        run: |
          echo "📋 CI Summary:"
          echo "  🐍 Quality: Code quality checks completed"
          echo "  🐳 Docker Test: Comprehensive Docker image testing"
          echo "  🔒 Security: Vulnerability scanning completed"
          echo "  📦 Publish: Images published to registries (main branch only)"
          echo "✅ All CI checks completed successfully!"
